.github/workflows/deploy.yml
.github/workflows/testing.yml
.github/workflows/update-precommit.yml
docs/src/user/changelog.rst
docs/src/user/codes/vasp.rst
docs/src/user/install.rst
src/atomate2/settings.py
src/atomate2/vasp/sets/core.py

The typos fixed in `{changelog,install}.rst` in 17e9070 will conflict with #105. Happy to remove those changes from this PR before merging but wanted to bring them up.

Bump GitHub actions to v3

---

docs/about/contributors.md

Tiny correction to contributors page (orcid and affiliation). @utf, thank for updating the contributors.

Small correction to contributors

---

docs/user/codes/vasp-workflows.csv
docs/user/codes/vasp.md
src/atomate2/vasp/flows/phonons.py
src/atomate2/vasp/jobs/phonons.py
src/atomate2/vasp/schemas/phonons.py

I updated the relevant files for the documentation of the phonon workflow.
Corrected the header in src/atomate2/vasp/flows/phonons.py
Added a header in src/atomate2/vasp/jobs/phonons.py and src/atomate2/vasp/schemas/phonons.py
Added a section concerning phonons in docs/user/codes/vasp.md
Added an entry in docs/user/codes/vasp-workflows.csv

Documentation of Phonon workflow

---

docs/user/codes/vasp-workflows.csv
docs/user/codes/vasp.md

I have added a few more lines of documentation for Lobster.
An additional question that is related: Should we also work on tutorials for certain, more complex flows?

Add more documentation for Lobster

---

docs/user/fireworks.md

This is to match and leverage the updates in the Jobflow docs.

Update FireWorks section of docs

---

docs/conf.py
pyproject.toml

Because I am lazy and hate having to highlight the code blocks.

Add a copy button to code blocks

---

.github/workflows/docs.yml

Deploy docs on every commit to `main`

---

docs/user/codes/vasp.md

I added more specific documentation for the Lobster worker. It should now be quite easy to experienced fireworks users to adapt to the Lobster workflow.
As this is a tiny change: 
@janosh or @utf
Thanks!

Add clearer documentation on lobster worker

---

pyproject.toml
src/atomate2/lobster/schemas.py

Adapts argument names as per latest LobsterPy release which breaks the Lobster workflow schema
Closes #468

Update CondensedBondingAnalysis schema

---

CHANGELOG.md
docs/about/contributors.md

I updated my username and did a find-and-replace here.

Update @arosen93 to @Andrew-S-Rosen

---

pyproject.toml

fixing pydantic v2 test errors

---

docs/about/contributors.md

Suggested by @janosh to remove first time contributor status in #562 
Add myself to the contributors list
* None
None
title.
your local machine. Start with running [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will
automatically reformat your code to PEP8 conventions and removes most issues. Then run
[ruff](https://ruff.rs).
Note that the CI system will run all the above checks. But it will be much more
efficient if …

Add Thomas Purcell to `contributors.md`

---

docs/about/contributors.md

Add @matthewkuner to contributors

---

docs/about/contributors.md

@janosh contrib to allow CI runs

[MAINT] contrib to allow CI runs

---

pyproject.toml

Use pypi mace

---

.github/workflows/deploy.yml
.github/workflows/docs.yml
.github/workflows/testing.yml
.pre-commit-config.yaml
pyproject.toml

Revert dependency on `ase` to PyPI release but install from `main` branch in CI

---

docs/user/codes/vasp.md

Recent schema update lead to change in outputs of Lobster task document as new models were added
Closes #680

Schema update > Update plot example LOBSTER workflow

---

pyproject.toml

-  New release of LobsterPy >  Fixes #681

Update lobsterpy version

---

src/atomate2/common/jobs/defect.py
src/atomate2/common/jobs/elastic.py
src/atomate2/common/jobs/phonons.py
src/atomate2/common/schemas/cclib.py
src/atomate2/common/schemas/elastic.py
src/atomate2/common/schemas/phonons.py
src/atomate2/forcefields/__init__.py
src/atomate2/forcefields/flows/relax.py
src/atomate2/forcefields/jobs.py
src/atomate2/forcefields/schemas.py
src/atomate2/lobster/schemas.py
src/atomate2/vasp/flows/md.py
src/atomate2/vasp/jobs/amset.py
src/atomate2/vasp/jobs/defect.py
src/atomate2/vasp/jobs/elph.py
src/atomate2/vasp/jobs/lobster.py
src/atomate2/vasp/schemas/elph.py
tests/vasp/flows/test_phonons.py
tests/vasp/jobs/test_md.py
tests/vasp/schemas/test_defect.py

Also support `mace-torch` in force field schema provenance for pkg version

Define `MLFF` `Enum` to ensure consistent force field names

---

CHANGELOG.md
README.md
citation.cff
tests/vasp/test_sets.py

closes #730.
first atomate2 Zenodo record: https://zenodo.org/records/10677081

Add `citation.cff` file, Zenodo record and readme "How to cite" section

---

pyproject.toml

Update LobsterPy version in standard installation

---

pyproject.toml

Remove emmet `==` pin in `pyproject.toml` and update version in `strict`

---

.pre-commit-config.yaml
src/atomate2/ase/utils.py
src/atomate2/common/flows/eos.py
src/atomate2/common/jobs/gruneisen.py
src/atomate2/common/schemas/phonons.py
src/atomate2/cp2k/schemas/calculation.py

[ Extracting value from dict without calling `.items()`](https://docs.astral.sh/ruff/rules/dict-index-missing-items/)

Fix `ruff` PLC0206

---

pyproject.toml

Calorine package version was not updated in main package dependencies (v3.0.0 supports latest version of ase, lower version does not)
Have updated the package version.

update calorine version

---

tutorials/grueneisen_workflow.ipynb
tutorials/phonon_workflow.ipynb
tutorials/phonon_workflow_aims.ipynb
tutorials/qha_workflow.ipynb

Fixes an issue in the gruneisen tutorial

fix gruneisen tutorial

---

tutorials/tutorials.md

fix a link in the tutorial link page

fix link again for aims tutorial

---

README.md

I am now more concrete for tutorial video names in the readme

be more concrete for tutorial video names in readme

---

README.md

Adding download statistics to readme

---

README.md

Fix zenodo link on readme

---

CODE_OF_CONDUCT.md

Hi @utf , 
I am proposing to update the code of conduct following this MP Foundation decision (https://github.com/materialsproject/foundation/pull/12).
Please let me know what you think.

Add code of conduct in accordance with MP Foundation recommmendation
