src/atomate2/vasp/schemas/calc_types/run_types.yaml
- I changed `MBJL` to `MBJ`. I think MBJ is the [supported keyword](https://www.vasp.at/wiki/index.php/METAGGA). Let me know if I'm wrong here.
- I added `RSCAN` and `R2SCAN` to the METAGGAs.
- I renamed `revPBE-vdW` to `vdW-DF` as suggested by the [VASP manual](https://www.vasp.at/wiki/index.php/VdW-DF_functional_of_Langreth_and_Lundqvist_et_al.). Happy to change this back if you think it's important to emphasize the revPBE part.
- I added `BEEF-vdW` since it's commonly used. Not sure what your thoughts are on having defaults set for "third-party" functionals.
=> Add some missing functionals

src/atomate2/vasp/schemas/calc_types/run_types.yaml
Very minor changes:
1. I hadn't noticed that you kept `LASPH = True` for the vdW functionals, so I added this flag for BEEF-vdW.
2. optB88-vdW was missing the `LASPH = True` flag, so I added it in. It's mentioned in the [VASP manual](https://www.vasp.at/wiki/index.php/VdW-DF_functional_of_Langreth_and_Lundqvist_et_al.).
=> Add missing LASPH flags on vdW functionals

src/atomate2/vasp/run.py
Previously, specifying the FULL_OPT job type for Custodian would never actually run because of a typo (see below). Now fixed.
https://github.com/materialsproject/atomate2/blob/6ef1188d9e1e038a6d964d8e9d9177c8e54727fd/src/atomate2/vasp/run.py#L147-L150
=> Custodian FULL_OPT fix

requirements.txt, tests/vasp/flows/test_core.py, tests/vasp/jobs/test_core.py
Updates test suite with correct energies so that pymatgen can be updated. Fixes (and can close) the error with #72.
=> Fix test suite for pymatgen vasprun fix

.gitignore, docs/src/user/codes/vasp.rst, docs/src/user/contributors.rst
Just cleaning up a few things in the documentation:
- Fixes some spelling mistakes I previously introduced in the VASP docs
- Added `docs_build/*` to `.gitignore` because that's the destination for the docs build folder when following the developer instructions 
- Fixed the ORCiD link (thanks for the credit!)
=> Fix a few typos in the docs

src/atomate2/vasp/files.py
It looks like there is an `potcar_spec` kwarg here
https://github.com/materialsproject/atomate2/blob/e7bfdb93cc3748c3465685fffd6efac8eba7257b/src/atomate2/vasp/sets/base.py#L73
which might be useful for live debugging, but `write_vasp_input_set` cannot use it since it breaks the input set creation here:
https://github.com/materialsproject/atomate2/blob/f319382ef47f4d4385d131cb2f9edefc24af83bf/src/atomate2/vasp/files.py#L171
This should allow you to write input files but it still looks like the KPOINTS file is missing.
Is this the expected behavior?
```
from atomate2.vasp.sets.core import RelaxSetGenerator
from atomate2.vasp.files import write_vasp_input_set
from pymatgen.core import Structure
mgo_structure = Structure(
lattice=[[0, 2.13, 2.13], [2.13, 0, 2.13], [2.13, 2.13, 0]], …
```
=> potcar spec kwarg

src/atomate2/vasp/schemas/calculation.py
`monty.os.path.which` is deprecated and will be removed in v2023. Replaced with `shutil.which`.
=> Replace monty which with shutil which

.pre-commit-config.yaml, README.md, docs/src/conf.py, setup.cfg, src/atomate2/common/schemas/cclib.py, src/atomate2/common/schemas/molecule.py, src/atomate2/common/schemas/structure.py, src/atomate2/vasp/jobs/amset.py, src/atomate2/vasp/schemas/task.py, src/atomate2/vasp/sets/base.py, tests/vasp/conftest.py
I was looking through the code trying to get a feel for the new atomate. 😄 
Noticed the default `ibands` value in `calculate_deformation_potentials()` will raise
```py
TypeError: 'NoneType' object is not iterable
```
https://github.com/materialsproject/atomate2/blob/c3d3fcd3e6edb8bb069cb0c23193ce1f356ed6b7/src/atomate2/vasp/jobs/amset.py
Happy to fix as part of this PR. Should `ibands` become a required arg?
=> Fix `calculate_deformation_potentials()`

src/atomate2/common/files.py, src/atomate2/utils/file_client.py
The current behavior will copy all files with a suffix `WSWQ.1` `WSWQ.2` to a single `WSWQ.gz` file since `path.with_suffix` just replaces the suffix.
I think gzipping should always keep the original suffix.
Also think the line in `find_and_filter_files` is a typo.
=> fixed gzipping of files like `WSWQ.1`

.github/workflows/deploy.yml, .github/workflows/docs_manual.yml, .github/workflows/testing.yml
`setup-python` has [built-in `pip` dependency caching](https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching).
Note caching was not working before as it [used the hash of non-existent `setup.py` as the cache key](https://github.com/materialsproject/atomate2/compare/main...janosh:ci-deps-caching?expand=1#diff-7dc87d4394e1756c519dbfd0b80d3b31377f643f0bc25d3ed807ce8a3794023dL53).
Equivalent PR to pymatgen: https://github.com/materialsproject/pymatgen/pull/2401
Also moves `codespell` pre-commit config to `setup.cfg`. I noticed `setup.cfg` was emptied in b82138e so I tried adding it to `pyproject.toml` instead but found that's not supported yet. Tracking issue: https://github.com/codespell-project/codespell/issues/2055
Curious why did you decide …
=> Configure CI to use `setup-python`'s built-in `pip` caching

docs/dev/vasp_tests.md, tests/vasp/conftest.py
This PR introduces two fixes related to the test system. 
- Fix `mock_run_vasp` to accept `*args` and `**kwargs` to match the signature of `run_vasp`. Otherwise, if a job maker sets some of these arguments (for example, the coming MD maker will set `handler`), the test will fail.  
- Fix doc on writing tests: changing the unit cell of the Si structure to avoid failing [check_poscar](https://github.com/materialsproject/atomate2/blob/a31b86b1e2f4d1a6665be7764c5cc67673904c91/tests/vasp/conftest.py#L200). In `check_poscar`, the `user` poscar will use a lattice of 
```
3.348898 0.000000 1.933487
1.116299 3.157372 1.933487
0.000000 0.000000 3.866975
```
while the `ref` poscar will use whatever lattice provided in the test file. The current doc on test suggests to use 
```
0.000000 2.730000 …
```
=> Fix mock_run_vasp to accept args and test docs

tests/common/test_jobs.py
Fix for test running via PRs. See discussion in #177. Hopefully this will do it!
=> Skip test if `MP_API_KEY` environment variable not set

src/atomate2/settings.py
Most interpreters will not automatically recognize the tilde. Use pathlib to expand the tilde into the absolute path for the default config file.
=> Patch: expanduser path

src/atomate2/lobster/schemas.py
Schema update
Issue -  LSO DOSCAR from lobster did not get added due to a missing file extension
Fix - update the schema to fix this issue
=> fix lso dos of lobster being not saved in schema

pyproject.toml, src/atomate2/lobster/schemas.py
- Added missing has_doscar_lso field to Lobsterout schema
=> add has_doscar_lso field to Lobsterout schema model and update lobsterpy version

src/atomate2/vasp/flows/defect.py
remove <hostname> while passing `dir_name` from bulk calculations
=> [Bug Fix] For stringing defect calculations together

src/atomate2/vasp/sets/BaseMPGGASet.yaml, src/atomate2/vasp/sets/BaseVaspSet.yaml
See https://github.com/materialsproject/pymatgen/issues/2968 for details.
=> Fix `Yb` PSP: change `Yb_2` to `Yb_3`

src/atomate2/common/schemas/cclib.py, tests/common/schemas/test_cclib.py
Closes #342. 
This is a copy of the now-closed #343 because I accidentally deleted the branch...
=> Add missing molecule field to cclib TaskDocument

docs/user/codes/vasp.md
I would like to refer to the new jobflow tutorials on fireworks addedin https://github.com/materialsproject/jobflow/pull/338 directly in the documentation of the Lobster workflow part. I think it is especially useful there.
=> Update Lobster documentation

src/atomate2/common/schemas/elastic.py, src/atomate2/vasp/flows/elastic.py, src/atomate2/vasp/jobs/elastic.py
Introduce a `task_document_kwarg` to the `ElasticDocument` that allows the elastic workflow to still complete in the event that the structure is elastically unstable. This specifically affects the `DerivedProperties` field in the ElasticDocument, which will be set to none in the event that the structure is elastically unstable.
@utf I made it so that elastically unstable structures are, by default, **_allowed_** to complete. Let me know if you think this should be changed.
=> allow elastically unstable structures

pyproject.toml, src/atomate2/common/schemas/elastic.py, src/atomate2/forcefields/flows.py, src/atomate2/forcefields/jobs.py, src/atomate2/forcefields/schemas.py, src/atomate2/vasp/flows/elastic.py, src/atomate2/vasp/jobs/elastic.py, tests/forcefields/test_jobs.py
* Add `M3GNet` support from the [matgl repository](https://github.com/materialsvirtuallab/matgl) to Atomate2 forcefields.
* matgl
* I do not plan to add support for MEGNet (as it seems to be inferior to M3GNet according to [matbench discovery](https://matbench-discovery.materialsproject.org/models)). Let me know if MEGNet has considerable demand too.
=> Add `m3gnet` support to Atomate2

src/atomate2/lobster/schemas.py
Tiny documentation change. As you can see, the amset schema led the development of the lobster schema.
=> clean up doc, remove left-overs from amset example

src/atomate2/amset/jobs.py, src/atomate2/common/schemas/cclib.py, src/atomate2/cp2k/jobs/base.py, src/atomate2/cp2k/jobs/core.py, src/atomate2/cp2k/schemas/task.py, src/atomate2/forcefields/schemas.py, src/atomate2/vasp/jobs/base.py, src/atomate2/vasp/jobs/core.py, src/atomate2/vasp/jobs/elastic.py, src/atomate2/vasp/jobs/phonons.py, src/atomate2/vasp/run.py, src/atomate2/vasp/sets/base.py, src/atomate2/vasp/sets/core.py, tests/vasp/flows/test_defect.py
There are a bunch more cases like
```py
if "parse_dos" not in self.task_document_kwargs:
self.task_document_kwargs["parse_dos"] = mode == "uniform"
if "parse_bandstructure" not in self.task_document_kwargs:
self.task_document_kwargs["parse_bandstructure"] = mode
if "additional_cp2k_files" not in self.copy_cp2k_kwargs:
self.copy_cp2k_kwargs["additional_cp2k_files"] = ("wfn",)
```
which can be simplified to
```py
self.task_document_kwargs.setdefault("parse_dos", mode == "uniform")
self.task_document_kwargs.setdefault("parse_bandstructure", mode)
self.copy_cp2k_kwargs.setdefault("additional_cp2k_files", ("wfn",))
```
Might get to them later.
=> `dict.setdefault` instead of `if key not in dict: dict[key] = ...`

.github/workflows/docs.yml, pyproject.toml, src/atomate2/vasp/sets/base.py, src/atomate2/vasp/sets/defect.py, tests/vasp/test_base.py
There's a strange interaction between charge-decorated structures and magmoms. 
Charge-decorated structures can `site.species.spin == None` which would lead to a result of `[None, ....]` for the `_get_magmoms` function and then lead to failure when writing the INCAR
=> [BUG FIX] Edge case for Magmoms

.github/workflows/docs.yml
Closes #454.
Needs a test run to make sure it works.
=> Use GitHub's `deploy-pages` action to deploy docs

src/atomate2/utils/file_client.py, src/atomate2/vasp/files.py, tests/common/test_files.py
Proposed change to make resuming of long-running calculations easier
If we want to resume a calculation
`VaspJob` in `custodian` has an `auto_continue` argument.  This makes sure that `CONTCAR` is copied to `POSCAR` whenever possible.
https://github.com/materialsproject/custodian/blame/26bf28a4b15b1253c955f3f8d6bd427bbc398e3a/custodian/vasp/jobs.py#L209-L229
So setting something like this at job creation or setting it in a restart script/CLI will be useful.
For a given maker:
```python 
BaseVaspMaker.run_vasp_kwargs = {"vasp_job_kwargs" : {"auto_continue" : True}}
```
However, most of the  VASP jobs in `atomate2` will copy from `prev_dir` first and thus overwrite the current state of the directory.  In most cases, this will just error out because `force_overwrite=False` by default.
For …
=> Small change to `gunzip` to allow better restarting

src/atomate2/vasp/sets/base.py, tests/vasp/test_sets.py
Fixes major bug that caused `user_incar_settings` to be overwritten in some cases.
=> [FIX] Fix major bug that caused `user_incar_settings` to be overwritten in some cases

tests/common/test_files.py
I mistakenly did not push the test for the `zip_outputs` function in #414. I just realized as I went back to the local repository. Sorry.
=> Test for zip_outputs

src/atomate2/vasp/sets/base.py, tests/vasp/test_sets.py
* Fixes issue in #505. Incar MAGMOM setting precedence now follows prescribed order.
* Adds test for `StaticSetGenerator` to catch this (method is in base class so should apply to other generators)
your local machine. Start with running [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will
automatically reformat your code to PEP8 conventions and removes most issues. Then run
[ruff](https://ruff.rs).
=> Enforce magmom precedence in INCAR creation

src/atomate2/common/schemas/elastic.py, src/atomate2/common/schemas/phonons.py, src/atomate2/lobster/schemas.py, src/atomate2/vasp/schemas/elph.py, tests/vasp/flows/test_elastic.py, tests/vasp/flows/test_elph.py, tests/vasp/flows/test_phonons.py, tests/vasp/lobster/schemas/test_lobster.py
As discussed in #502 I added StructureMetadata to some of the final documents, i.e. `ElasticDocument`, `PhononBSDOSDoc`, `LobsterTaskDocument`, `ElectronPhononRenormalisationDoc`. I wanted to add it for the output of the defect flow as well, but I am not sure if there is a meaningful place to add it.
=> Add StructureMetadata as baseclass for output documents

src/atomate2/settings.py, tests/common/test_settings.py
Closes #499.
This PR is closely inspired by https://github.com/materialsproject/jobflow/pull/415. Thanks @mcgalcode! 👍
=> Warn on empty config

src/atomate2/cp2k/schemas/task.py, src/atomate2/forcefields/jobs.py, src/atomate2/forcefields/schemas.py, tests/cp2k/jobs/test_core.py
=> CP2K use `calcs_reversed[0]` instead of `calcs_reversed[-1]` to not reverse again

.github/workflows/testing.yml, .github/workflows/update-precommit.yml, pyproject.toml
1. Remove Python 3.8 support
2. Add python 3.11 
Closes #530
=> removed py38 support, and add py 3.11 support

src/atomate2/common/schemas/defects.py, src/atomate2/common/schemas/phonons.py, src/atomate2/cp2k/schemas/calculation.py, src/atomate2/cp2k/schemas/task.py, src/atomate2/lobster/schemas.py, tests/forcefields/test_jobs.py
* WIP PR to close #548
title.
your local machine. Start with running [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will
automatically reformat your code to PEP8 conventions and removes most issues. Then run
[ruff](https://ruff.rs).
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended that you use …
=> Fix failing tests from Pydantic v2 migration

src/atomate2/common/flows/defect.py, src/atomate2/common/jobs/defect.py, tests/vasp/flows/test_defect.py
For #548 
Looks like the pydanctic2 PR is blocked by the defect formation energy test.
This fixes one of the problems:
- The defect charge state sanity check requires the POTCAR data but we only have POTCAR spec so we cannot assign charge automatically.  Prior versions of atomate2 did not give a CI failure for this.  The particular job to check the charge state still failled but the CI is able to pass. 
But there seems to be a second problem that I'm not sure about:
- The`bulk_summary["sc_entry"]` which comes directly from TaskDoc of the relaxation job now gives `None`
Other fields for `bulk_summary` seems to be OK. 
```python
relax_output: TaskDoc = relax_job.output
summary_d = {
"uc_structure": uc_structure,
"sc_entry": relax_output.entry,
"sc_struct": relax_output.structure,
```
This …
=> skip validate charge test

docs/about/contributors.md
As mentioned in https://github.com/materialsproject/atomate2/pull/137, Alexander Bonkowski (@ab5424) has contributed to the phonon workflow in atomate2. I based the implementation in atomate2 partially on work from his Master thesis. Therefore, I would like to add him to the list of contributors of atomate2.
=> Add Alex Bonkowski to contributors list

src/atomate2/vasp/powerups.py, src/atomate2/vasp/sets/base.py, tests/vasp/test_sets.py
Closes #465.
A few key changes:
- Added new function, `update_vasp_input_generators` to `vasp.powerups` to remove repeated code. All subsequent functions, such as `update_user_incar_settings` now rely on this base function
- Fixed broken logic in `VaspInputGenerator._get_incar`: in `_get_incar`, `_set_kspacing` was called with `previous_incar is None` which is never true, because `previous_incar = previous_incar or {}` at the top of `_get_incar`. More, this would imply that no previous incar was found, which means `from_prev` in `_set_kspacing` was its inverse. Should be `previous_incar != {}` to indicate the presence of a previous calc
- After some discussion with @Andrew-S-Rosen , we noticed that `vasp.sets.base._get_kspacing` should return `min(kspacing, 0.44)`, to ensure that if …
=> Clean up VASP powerups, correct params in MP flows, test for `_set_u_params`, test for `_set_kspacing`, fix `_get_incar` method of `VaspInputSet`

.pre-commit-config.yaml, pyproject.toml, src/atomate2/amset/schemas.py, src/atomate2/cp2k/schemas/calculation.py, src/atomate2/forcefields/jobs.py, src/atomate2/settings.py, src/atomate2/vasp/sets/base.py, tests/cp2k/conftest.py, tests/vasp/conftest.py, tests/vasp/flows/test_phonons.py, tests/vasp/lobster/conftest.py
Follow up to #578. Make sure we use future type annotation in all non-schema files and bump `ruff` target version to 3.9.
=> Future type annotations

src/atomate2/cli/dev.py, src/atomate2/cp2k/schemas/calc_types/utils.py, tests/forcefields/flows/test_phonon.py, tests/vasp/flows/test_elastic.py, tests/vasp/flows/test_elph.py, tests/vasp/flows/test_phonons.py, tests/vasp/jobs/test_core.py, tests/vasp/lobster/schemas/test_lobster.py
For much better error messages
```py
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0.05
Mismatched elements: 5 / 5 (100%)
Max absolute difference: 20.93780092
Max relative difference: 0.00351895
x: array([ 5076.241999,  5402.944837,  6781.803129,  8742.033493,
10939.957742])
y: array([ 5058.441588,  5385.880586,  6765.198542,  8723.785881,
10919.019941])
```
vs previously
```py
AssertionError: assert False
```
Related PR https://github.com/materialsproject/pymatgen/pull/3253.
=> Use `numpy.testing.assert_allclose` over assert `np.(all|is)close`

src/atomate2/lobster/jobs.py, src/atomate2/vasp/flows/lobster.py
Closes #572 
It's not solving potential related issues with jobflow but a solution for the Lobster workflow. We don't need to save the band structure of DOS from VASP in this case. (Actually, only the BandStructure does not end up in the data store which is something I cannot really understand).
The gzip error was initially resolved by @naik-aakash as a part of his larger PR. However, I would very much appreciate it if this fix could be merged rather quickly.
I also fixed a tiny issue in the documentation that I had forgotten the last time.
=> Fix Lobster workflow

pyproject.toml, src/atomate2/common/schemas/elastic.py, src/atomate2/cp2k/flows/core.py, src/atomate2/cp2k/run.py, src/atomate2/lobster/run.py, src/atomate2/vasp/flows/core.py, src/atomate2/vasp/flows/matpes.py, src/atomate2/vasp/run.py, tests/vasp/flows/test_matpes.py, tests/vasp/flows/test_mp.py, tests/vasp/flows/test_phonons.py, tests/vasp/jobs/test_matpes.py, tests/vasp/jobs/test_mp.py
Change `MatPesGGAPlusMetaGGAStaticMaker.output` from `static2.output` to `{"static1": static1.output, "static2": static2.output}`. Brings it more in line with e.g. `BandStructureMaker`:
https://github.com/materialsproject/atomate2/blob/5aced196baf8bbbf41875cbd19836c09069611bf/src/atomate2/vasp/flows/core.py#L143-L156
ac67d333 pytest addopts = "-p no:warnings --import-mode=importlib"
4a7a9428 fix should_stop_children RuntimeError err msg calling handle_unsuccessful defuse_unsuccessful
7f6219a8 MatPesGGAPlusMetaGGAStaticMaker change output from static2.output to {"static1": static1.output, "static2": static2.output}
e47db541 test_matpes_gga_plus_meta_gga_static_maker assert isinstance(flow.output, dict)
5aced196 rename output to task_doc in matpes and mp tests
=> Change `MatPesGGAPlusMetaGGAStaticMaker.output` to dict containing both statics

src/atomate2/vasp/sets/mp.py, tests/common/schemas/test_cclib.py, tests/cp2k/jobs/test_core.py, tests/forcefields/flows/test_elastic.py, tests/forcefields/flows/test_phonon.py, tests/forcefields/test_jobs.py, tests/vasp/flows/test_phonons.py, tests/vasp/jobs/test_matpes.py, tests/vasp/jobs/test_mp.py, tests/vasp/lobster/schemas/test_lobster.py, tests/vasp/sets/test_matpes.py, tests/vasp/sets/test_mp.py, tests/vasp/test_sets.py
We already had tests for MP and MatPES jobs and flows but none for the set generators. Felt more necessary after the `inherit_incar` default change in #594 in case other defaults change in the future that might affect the MP/MatPES input sets.
cbc11e4a add `tests/vasp/sets/test_mp.py`
3364f6aa fix: add missing `bandgap_tol: float = 1e-4` default to `MPMetaGGAStaticSetGenerator`
9e1b269e add `tests/vasp/sets/test_matpes.py`
50b0313b remove excess float precision of more than 8 decimal points in tests
=> Test MP + MatPES set generators

src/atomate2/amset/jobs.py, src/atomate2/common/flows/defect.py, src/atomate2/common/flows/elastic.py, src/atomate2/common/jobs/defect.py, src/atomate2/common/jobs/phonons.py, src/atomate2/common/utils.py, src/atomate2/cp2k/flows/core.py, src/atomate2/cp2k/jobs/base.py, src/atomate2/cp2k/jobs/core.py, src/atomate2/forcefields/jobs.py, src/atomate2/vasp/flows/amset.py, src/atomate2/vasp/flows/core.py, src/atomate2/vasp/flows/elastic.py, src/atomate2/vasp/flows/elph.py, src/atomate2/vasp/flows/lobster.py, src/atomate2/vasp/flows/matpes.py, src/atomate2/vasp/flows/mp.py, src/atomate2/vasp/flows/phonons.py, src/atomate2/vasp/jobs/amset.py, src/atomate2/vasp/jobs/base.py, src/atomate2/vasp/jobs/core.py, src/atomate2/vasp/jobs/elph.py, src/atomate2/vasp/jobs/lobster.py
As discussed in today's `atomate2` maintainer meeting, it would be great to unify the API between `Makers` for different codes and forcefields to more easily swap, say, a PBEsol pre-relax maker for a forcefield pre-relax maker and not have to worry about the flow that stitches the makers together passing in an unrecognized keyword like `prev_vasp_dir` into the forcefield maker.
=> Breaking: Unify previous directory `Maker` API

src/atomate2/vasp/jobs/base.py
Closes https://github.com/materialsproject/atomate2/issues/584. 
I added "bandstructure" to the list of object names that should be saved in the datastore. I think it is related to how emmet saves the bandstructures:
https://github.com/materialsproject/emmet/blob/08f143833ac6ba5732abadb7beee9e424d0220cf/emmet-core/emmet/core/vasp/calculation.py#L49
For DOS, I assume it works by accident.
=> Resolve bandstructure datastore bug

src/atomate2/cp2k/schemas/calculation.py, src/atomate2/forcefields/schemas.py, src/atomate2/settings.py, src/atomate2/vasp/jobs/base.py, tests/common/test_settings.py, tests/vasp/flows/test_phonons.py
Similar to existing setting `VASP_RUN_BADER`, allows saving DDEC6 charge analysis automatically in any VASP `TaskDoc`.
https://github.com/materialsproject/atomate2/blob/a3215dbe6dcd094eb4dfdff51d77dbdf71530f33/src/atomate2/settings.py#L82
Related PR https://github.com/materialsproject/emmet/pull/869
=> Add setting `VASP_RUN_DDEC6: bool = False`

pyproject.toml, src/atomate2/forcefields/jobs.py, src/atomate2/vasp/flows/phonons.py, tests/forcefields/flows/test_elastic.py, tests/forcefields/test_jobs.py
c74e0f1a MACE `Static/RelaxMakers` default to loading `mace_mp` instead of test model
29c80627 parametrize `model_path` in `test_mace_static_maker` and `test_mace_relax_maker`
Needs https://github.com/ACEsuit/mace/pull/230 to start working.
=> MACE Static/RelaxMakers default to loading `mace_mp` instead of test model

.pre-commit-config.yaml, src/atomate2/forcefields/flows/phonons.py, src/atomate2/forcefields/jobs.py, src/atomate2/forcefields/schemas.py, tests/forcefields/test_jobs.py
As agreed with @JaGeo, this PR changes the default `relax_cell` from `False` to `True` on `ForceFieldRelaxMaker` and all its subclasses.
=> `ForceFieldRelaxMaker` default `relax_cell` to `True`

src/atomate2/common/schemas/phonons.py, src/atomate2/forcefields/flows/phonons.py, src/atomate2/vasp/flows/phonons.py, src/atomate2/vasp/jobs/elastic.py, tests/forcefields/flows/test_phonon.py, tests/vasp/flows/test_phonons.py
Motivation: Most people likely won't use the `thermal_displacement_matrix` resulting from `create_thermal_displacements=True` but having it on can cause the calculation to fail [due to this line in `phonopy`'s](https://github.com/phonopy/phonopy/blob/4b0b2e5ea7c88d9a184bf72411be210d996ab602/phonopy/phonon/thermal_displacement.py#L405) `_get_disp_matrices`
```
assert (abs(disps.imag) < 1e-1).all()
```
This change was discussed with @JaGeo but pinging her for final approval.
Full stack trace
```py
INFO:jobflow.managers.local:generate_frequencies_eigenvectors failed with exception:
Traceback (most recent call last):
File "/Users/janosh/dev/jobflow/src/jobflow/managers/local.py", line 106, in _run_job
response = job.run(store=store)
^^^^^^^^^^^^^^^^^^^^
File …
```
=> Default `create_thermal_displacements` to `False` in VASP and forcefield `PhononMaker`

.pre-commit-config.yaml, pyproject.toml
@utf IIUC, `flake8` last remaining use was to lint python code in rST files? I see only 5 rST files and none of them contain Python code. Combined with the fact that [`ruff` now lints Python in doc strings](https://astral.sh/blog/ruff-v0.1.8), I think we can get rid of `flake8` entirely. Let me know if I missed something.
=> Drop `flake8`

src/atomate2/common/schemas/phonons.py, tests/common/schemas/test_elastic.py, tests/common/schemas/test_phonons.py, tests/vasp/flows/test_phonons.py
@JaGeo Can we add an optional  `material_id: str | int` to `PhononBSDOSDoc` to facilitate provenance?
An alternative could be setting
```diff
- class PhononBSDOSDoc(StructureMetadata):
+ class PhononBSDOSDoc(StructureMetadata, extra="allow"):
```
to allow users to set arbitrary additional fields.
=> Set `extra="allow"` on `PhononBSDOSDoc`

src/atomate2/common/schemas/phonons.py
Currently, the path to the folder where the task doc and phonopy output files have been generated is not added to the list of directories of the output of the phonon run. This makes collecting all data unnecessarily hard. I have now added this directory path as well.
=> add directory of task doc generation to phonon schema

docs/user/fireworks.md
Link to Jobflow examples did not work due to use of `()` instead of `[]`. Which is fixed now
=> Fix hyperlink in Docs

src/atomate2/vasp/sets/base.py, tests/cp2k/conftest.py, tests/vasp/lobster/schemas/test_lobster.py
Many `pymatgen` classes had inconsistently named `get/from_(str|string)` methods. `get/from_string` was deprecated in favor of `get/from_str` 6 months ago and removed last week in https://github.com/materialsproject/pymatgen/pull/3561 which will be released this or next week.
@utf this change will require a new `atomate2` version to be compatible with the upcoming `pymatgen`.
resulting `AttributeError` incurrent `atomate2` reported by @abhardwaj73 in https://github.com/materialsproject/pymatgen/issues/3571#issuecomment-1911066021. thanks!
=> Prep for next `pymatgen` release

src/atomate2/common/jobs/defect.py
Make the check for the shape of the reference suprecell matrix more explicit.
Under the old code, it is possible to have two sc of the exact same shape.
The exact example is given below
```
ipdb> print(uc_structure.lattice)
5.090004 -0.000001 -0.000007
2.545003 -4.408073 -0.000007
2.545009 -1.469362 -4.595759
ipdb> print(sc_mat_ref)
[[2, 0, 0], [2, -3, 0], [1, 1, -3]]
ipdb> print(sc_mat_prv)
[[-2  2  0]
[-2 -1  0]
[-1 -1  3]]
ipdb> print(sc_ref.lattice.abc, sc_ref.lattice.angles)
(10.180005983446268, 13.466886920683072, 13.787261249420052) (90.0001838526074, 89.99999983000444, 79.10660876819587)
ipdb> print(sc_prv.lattice.abc, sc_prv.lattice.angles)
(10.180005983446268, 13.466886920683072, 13.787261249420052) (90.0001838526074, 89.99999983000444, 79.10660876819587)
```
=> [bug fix] SC Matrix Checking Logic

src/atomate2/vasp/sets/matpes.py
It said GGA when it should have said meta-GGA. Trivial. CC @janosh.
=> Fix docstring on `MatPesMetaGGAStaticSetGenerator`

src/atomate2/vasp/sets/base.py
Closes #726. 
Relaxing a metal with ISMEAR = 0 is fine, as noted in the VASP manual, provided SIGMA is sufficiently small (< 0.05 is the recommendation in the VASP manual).
> If you have no a priori knowledge of your system, for instance, if you do not know whether your system is an insulator, semiconductor or metal then always use Gaussian smearing ISMEAR=0 in combination with a small [SIGMA](https://www.vasp.at/wiki/index.php/SIGMA)=0.03-0.05.
=> Modify `BadInputSetWarning` logic for relaxations of a likely metal

.pre-commit-config.yaml, src/atomate2/common/files.py, src/atomate2/common/schemas/cclib.py, src/atomate2/cp2k/schemas/calc_types/utils.py, src/atomate2/cp2k/schemas/calculation.py, src/atomate2/cp2k/sets/base.py, src/atomate2/forcefields/flows/phonons.py, src/atomate2/lobster/schemas.py, src/atomate2/utils/file_client.py, src/atomate2/vasp/files.py, src/atomate2/vasp/flows/phonons.py, src/atomate2/vasp/sets/base.py, tests/common/schemas/test_defect.py, tests/common/test_files.py, tests/cp2k/sets/test_core.py, tests/vasp/flows/test_phonons.py
dbd7e991 `PhononMaker` print invalid values and list valid ones in for `kpath_scheme`, `use_symmetrized_structure`
37750762 fix `cclib_calculate()` wrong err msg claiming to `return None` when actually raising
f20c68e1 prefer tuple for static sequence literal
bd9b02a7 assert unused ret val distances in `test_sort_pos_dist()`
0f326f52 simplify dict construction in lobster `read_saved_json()`, `LobsterTaskDocument.from_directory`
=> Print invalid value and list valid ones in `PhononMaker` error messages

tests/forcefields/test_utils.py
Currently installing on a new system.
Noticed a couple of bugs during testing:
- The `assert_allclose` is missing `atol` which errors out on some systems.
- Ase must be installed with `ase-core` first then `ase`, otherwise a large number of tests fail. (Not sure how to fix this)
The following asa packages, installed in order, allowed the tests to pass without linking to the gitlab repo for ase.
```
ase-core                  3.23.0b1.post3
ase                       3.22.1
```
=> [BUGFIX] Minor test and install bugs

src/atomate2/aims/files.py, src/atomate2/aims/flows/core.py, src/atomate2/aims/flows/gw.py, src/atomate2/aims/flows/phonons.py, src/atomate2/aims/jobs/core.py, src/atomate2/aims/jobs/phonons.py, src/atomate2/aims/run.py, src/atomate2/aims/schemas/calculation.py, src/atomate2/aims/schemas/task.py, src/atomate2/aims/utils/__init__.py, src/atomate2/aims/utils/bands.py, src/atomate2/aims/utils/units.py, src/atomate2/common/flows/eos.py, src/atomate2/common/jobs/eos.py, src/atomate2/forcefields/flows/eos.py, src/atomate2/forcefields/jobs.py, src/atomate2/forcefields/utils.py, src/atomate2/vasp/flows/electrode.py, src/atomate2/vasp/flows/phonons.py, src/atomate2/vasp/jobs/phonons.py, tests/aims/test_flows/test_core.py, tests/aims/test_flows/test_gw_convergence.py, tests/aims/test_flows/test_phonon_workflow.py, tests/aims/test_makers/test_convergence.py, tests/aims/test_makers/test_static.py, tests/vasp/flows/test_eos.py
`revert_default_dtype` context manager used in `MACE(Relax|Static)Makers` reverts `torch.dtype` to whatever it was when context was entered to prevent MACE from clashing with other torch force fields (CHGNet, M3GNet) running in the same session.
Not ideal as a long-term solution but currently the cleanest workaround to the issue reported in https://github.com/ACEsuit/mace/issues/328. thanks @hatemhelal [for suggesting](https://github.com/ACEsuit/mace/issues/328#issuecomment-1980563820) this fix.
=> Add `revert_default_dtype` context manager to fix clashing global `torch.dtype` between MACE and CHGNet

CHANGELOG.md, src/atomate2/aims/files.py, src/atomate2/aims/flows/phonons.py, src/atomate2/common/schemas/elastic.py, src/atomate2/vasp/run.py, src/atomate2/vasp/sets/base.py, tests/common/jobs/test_elastic.py, tests/vasp/flows/test_eos.py, tests/vasp/test_base.py
prefix "_" indicates private but cross-imported means de facto public.
strictly speaking breaking if downstream code was importing these private symbols but given they were marked private there was no expectation of stability.
=> Make functions prefixed with `_` but cross-imported public

.pre-commit-config.yaml, src/atomate2/settings.py, tests/common/test_settings.py
just a small QoL improvement to warn users when they set a custom `ATOMATE2_CONFIG_FILE` but the file doesn't exist
@utf i added tests to assert
- no warning if config path is default and file does not exist
- warning if config path is non-default and file does not exist
also  used `monkeypatch.setenv("ATOMATE2_CONFIG_FILE", ...)` which is auto-reverted on test-exit to avoid polluting other tests
=> Warn on non-default `ATOMATE2_CONFIG_FILE` that's not found

docs/user/install.md
=> Add more details to the installation guide

src/atomate2/forcefields/jobs.py, src/atomate2/forcefields/utils.py, src/atomate2/vasp/flows/md.py, src/atomate2/vasp/jobs/lobster.py, tests/forcefields/test_utils.py
=> Add missing `calculator_kwargs` and remove outdated `model`/`model_kwargs` in `ForceFieldRelaxMaker` doc strings

docs/dev/workflow_tutorial.md, pyproject.toml, src/atomate2/forcefields/jobs.py, src/atomate2/forcefields/md.py, src/atomate2/forcefields/utils.py, tests/forcefields/test_md.py
=> Turn `ForceFieldRelaxMaker._calculator` method into `calculator` property

src/atomate2/abinit/utils/common.py, src/atomate2/abinit/utils/history.py, src/atomate2/aims/jobs/convergence.py, src/atomate2/aims/schemas/task.py, src/atomate2/amset/schemas.py, src/atomate2/cli/dev.py, src/atomate2/cp2k/files.py, src/atomate2/cp2k/schemas/calculation.py, src/atomate2/forcefields/utils.py, src/atomate2/qchem/files.py, src/atomate2/utils/file_client.py, src/atomate2/vasp/files.py, tests/abinit/conftest.py, tests/abinit/sets/test_base.py, tests/abinit/sets/test_core.py, tests/cp2k/sets/test_base.py, tests/forcefields/test_md.py, tests/vasp/flows/test_defect.py, tests/vasp/jobs/test_core.py
`TrajectoryObserver.to_ase_trajectory` does not return `ase.io.Trajectory` (as prev annotated) which (confusingly) is a function but an `ase.io.trajectory.TrajectoryReader` instance
=> Fix `TrajectoryObserver.to_ase_trajectory` return type

src/atomate2/common/jobs/phonons.py
Currently, the supercells that are generated with the phonon workflow are sometimes not as cubic as possible (e.g., for diamond-type Si). This is due to a bug in the supercell matrix handling. The supercell matrix as determined by pymatgen needs to be transposed before it is inserted into phonopy.
=> Bug in supercell matrix determination in phonon workflow

src/atomate2/cli/dev.py
Fix the error:
```
File "/home/atomate2/src/atomate2/cli/dev.py", line 58, in vasp_test_data
if not isinstance(output["output"], TaskDoc):
~~~~~~^^^^^^^^^^
TypeError: 'JobStoreDocument' object is not subscriptable
```
=> Fix JobStoreDocument attribute access 

src/atomate2/cp2k/schemas/calc_types/utils.py, src/atomate2/cp2k/schemas/calculation.py
This PR addresses the ValidationError occurring in the TaskDocument schema due to improper handling of the cp2k_input and locpot fields. This issue is documented in issue #899 
* Changed `cp2k_input` in CalculationInput to be a union of `CP2KInput` object and dict to accommodate different possible types for cp2k_input
* Changed `locpot` in CalculationOutput to be an optional field
=> fix CP2K TaskDocument

src/atomate2/common/schemas/phonons.py
Closes #904
1. Add `additional_fields` as an acceptable kwargs to `generate_frequencies_eigenvectors_kwargs` (users can add metadata to the output taskdoc from here)
1.  Should we rename the `generate_frequencies_eigenvectors_kwargs` to `task_document_kwargs`? This will help us use the powerups to add the metadata, but it would be a big change to the current workflow implementation. What do you think?
=> add additional fields as kwargs to PhononBSDOSDoc

src/atomate2/lobster/schemas.py
1. Change field name `schema `to `atomate2_version `
2. Adapt `zpath `obtained via `monty `to work even with recent version of the monty package
=> Lobster schema updates

pyproject.toml, src/atomate2/vasp/sets/matpes.py, src/atomate2/vasp/sets/mp.py
following input set migration to `pymatgen` in #854, flows serialized to a database before that PR can no longer be instantiated and launched with the latest `atomate2` resulting in a `TypeError`
```py
"/lambdafs/janosh/.venv/p312/lib/python3.12/site-packages/monty/json.py",    
line 790, in process_decoded                                                 
return cls_.from_dict(data)                                              
^^^^^^^^^^^^^^^^^^^^                                              
File                                                                       
"/lambdafs/janosh/.venv/p312/lib/python3.12/site-packages/monty/json.py",    
line 245, in from_dict                                                       
k: MontyDecoder().process_decoded(v) …
```
=> Add back `symprec` kwarg to MP and MatPES set generators

docs/user/install.md
Using JSONStore instead of MongoDB. 
* `yaml` file for JSONStore
* Info about the attributes and limitation of `JSONStore`
=> Added documentation about JSONStore usage within Installation

README.md
=> Remove README note about atomate2 mostly being for VASP

src/atomate2/common/jobs/electrode.py, tests/vasp/flows/test_electrode.py
Minor bugfix: in `atomate2.common.jobs.electrode`, the utility functions `get_computed_entries`, `get_structure_group_doc`, and `get_insertion_electrode_doc` assign MPIDs via UUIDs, which leads to pydantic errors when the documents are serialized (an MPID has to have the form `mp-<int>`).
Thanks to @RobertaPascazio for catching this. Copy @jmmshn  to make sure this is still compliant with the flow format.
=> Fix MPID assignment in electrode workflow

src/atomate2/vasp/jobs/mp.py, tests/vasp/jobs/test_mp.py
=> Fix `prev_dir` behavior in input set generator of `MPGGAStaticMaker`

src/atomate2/openmm/jobs/base.py, src/atomate2/openmm/jobs/core.py, tests/openmm_md/flows/test_core.py, tests/openmm_md/jobs/test_base.py, tests/openmm_md/jobs/test_core.py, tests/openmm_md/jobs/test_generate.py
Previously the energy minimization maker didn't have any way of reporting energies. This fixes that.
Implemented:
=> Allow energy minimization maker to report energies

tests/aims/test_flows/test_phonon_workflow.py
Fix the phonon workflow test for FHI-aims: Remove os environment call
None
title.
your local machine. Start with running [`ruff`](https://docs.astral.sh/ruff) and `ruff format` on your new code. This will
automatically reformat your code to PEP8 conventions and fix many linting issues.
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly …
=> Fix aims phonon flow test

pyproject.toml
This is a simple update to the MACE version, as mentioned in PR #1023.
title.
your local machine. Start with running [`ruff`](https://docs.astral.sh/ruff) and `ruff format` on your new code. This will
automatically reformat your code to PEP8 conventions and fix many linting issues.
Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended …
=> Update MACE to 0.3.6

pyproject.toml
Add FireWorks dependency as a separate optional dependency
group. This allows users to explicitly install FireWorks components with
`pip install atomate2[fireworks]` and makes the dependency structure more
modular and clear.
Fix https://github.com/materialsproject/atomate2/issues/1033
=> feat: add dedicated fireworks optional dependency (Fix #1033).

docs/user/codes/index.md
Currently, OpenMM is not showing up under docs as it is not part of the index.md
=> add openmm description to docs

docs/user/codes/vasp.md, src/atomate2/forcefields/__init__.py, src/atomate2/forcefields/flows/elastic.py, src/atomate2/forcefields/flows/eos.py, tests/forcefields/flows/test_elastic.py, tests/forcefields/test_utils.py
Three smaller changes:
- Update VASP EOS section of the docs to explain the makers / sets there, close issue [#1071](https://github.com/materialsproject/atomate2/issues/1071#issuecomment-2500931796)
- Add a convenience constructor method, `from_force_field_name` to `ElasticMaker` as suggested by @utf  in [#999](https://github.com/materialsproject/atomate2/pull/999#issuecomment-2382426247)
- Allow the forcefield name enum `MLFF` to permit `str(MLFF.<member>)` as valid input. This should hopefully resolve some issues noted by @tjaffrel when running forcefield jobs from fireworks
=> Docs update, forcefield elastic convenience maker, forcefield enum hydration

src/atomate2/vasp/sets/core.py
`Structure.ntypesp`  was replaced by `Structure.n_elems`
https://github.com/materialsproject/pymatgen/pull/3562
This PR allows for both of those within atomate2 for now.
=> Deprecated `Structure.ntypesp` in pymatgen

README.md, docs/index.md
A while ago I had written [this tutorial](https://materialsproject.github.io/atomate2/user/key_concepts_overview.html#key-concepts-in-atomate2-job-flow-makers-inputset-taskdocument-and-builder) (https://github.com/materialsproject/atomate2/pull/757) but didn't link it somewhere to be found. 😅
=> Add key concept tutorial to tutorial list in README

docs/user/key_concepts_overview.md
sorry, that I have to make another PR, in the last one I didn't adjust the headline levels, so the doc sidebar is a bit messed up now 😅
=> Fixing headline levels in key_concepts_overview.md

pyproject.toml, tutorials/grueneisen_workflow.ipynb, tutorials/lobster_workflow.ipynb, tutorials/qha_workflow.ipynb, tutorials/tutorials.md
Small modifications on the documentation and the tutorial headlines.
=> add more headlines to tutorials and fix a typo

.github/workflows/docs.yml, pyproject.toml, src/atomate2/ase/jobs.py, src/atomate2/ase/md.py, src/atomate2/ase/schemas.py, src/atomate2/ase/utils.py, src/atomate2/forcefields/__init__.py, src/atomate2/forcefields/jobs.py, src/atomate2/forcefields/utils.py, tests/ase/test_jobs.py, tests/ase/test_utils.py, tests/forcefields/test_jobs.py, tests/forcefields/test_md.py
- Adds MatPES-trained PBE and r<sup>2</sup>SCAN MLFFs with options to use different pre-trained model architectures
- Adds tests
- Slight tweak to base `AseMaker` class per the atomate2 workshop - this class just now needs a calculator plugged in to run a static / external interface to another code. Useful for examples in training / simple ASE stuff
Would also close #1156
=> Add MatPES forcefields

src/atomate2/lobster/schemas.py
LOBSTER run results sometimes not consistent when using POSCAR as VASP sometimes shifts origin leading to inconsistent neighbour detections
=> switch to CONTCAR read for LOBSTERTaskDoc

src/atomate2/common/flows/mpmorph.py, src/atomate2/common/jobs/eos.py, tests/ase/flows/test_mpmorph.py
Fixes a bug in `mpmorph.py`. 
```Python
v0_in_range = (
(vmin := working_outputs.get("Vmin"))
<= v0
<= (vmax := working_outputs.get("Vmax"))
)
```
If `v0 > vmin`, the expression evaluates to false and the second comparison is skipped, leaving `vmax` unassigned. 
I moved the two assignments out of the expression, avoid the walrus operators. 
title.
your local machine. Start with running [`ruff`](https://docs.astral.sh/ruff) and `ruff format` on your new code. This will
automatically reformat your code to PEP8 conventions and fix many linting …
=> Remove walrus operator to avoid unassigned vmax

src/atomate2/vasp/sets/core.py, tests/vasp/test_sets.py
`RelaxConstVolSetGenerator` was not setting the INCAR values correctly.
Fixing this and adding tests for all the input sets in core to avoid this kind of issues.
=> Fix RelaxConstVolSetGenerator

src/atomate2/openff/schemas.py, src/atomate2/openmm/flows/core.py, src/atomate2/openmm/flows/dynamic.py, src/atomate2/openmm/interchange.py, src/atomate2/openmm/jobs/base.py, src/atomate2/openmm/jobs/generate.py, src/atomate2/openmm/utils.py, tests/openmm_md/conftest.py, tests/openmm_md/flows/test_core.py, tests/openmm_md/jobs/test_core.py, tests/openmm_md/jobs/test_generate.py, tests/openmm_md/test_utils.py
Related to emmet-core PR [#1274](https://github.com/materialsproject/emmet/pull/1274): a few unused, in-development schemas related to solvation are being migrated to atomate2 pending workflow development. The goal is to make emmet-core and builders independent of more third-party codes, such as openmm, openff, and MDAnalysis
Also migrates the Interchange class, which is a workflow object and not a document model, to atomate2
=> Migrate developmental OpenMM / OpenFF schemas from emmet-core
